# Exported from Render on 2026-03-29T09:25:39Z
version: "1"
services:
- type: web
  name: erp
  runtime: docker
  repo: https://github.com/sech444/erp
  plan: free
  envVars:
  - key: NEXT_PUBLIC_APP_NAME
    sync: false
  - key: NEXT_PUBLIC_API_URL
    sync: false
  - key: FROM_NAME
    sync: false
  - key: FROM_EMAIL
    sync: false
  - key: SMTP_PASS
    sync: false
  - key: SMTP_USER
    sync: false
  - key: SMTP_PORT
    sync: false
  - key: SMTP_HOST
    sync: false
  - key: STORAGE_ENDPOINT
    sync: false
  - key: STORAGE_SECRET_KEY
    sync: false
  - key: STORAGE_ACCESS_KEY
    sync: false
  - key: STORAGE_REGION
    sync: false
  - key: STORAGE_BUCKET
    sync: false
  - key: STORAGE_PROVIDER
    sync: false
  - key: API_PREFIX
    sync: false
  - key: NODE_ENV
    sync: false
  - key: PORT
    sync: false
  - key: JWT_REFRESH_EXPIRES
    sync: false
  - key: JWT_ACCESS_EXPIRES
    sync: false
  - key: JWT_REFRESH_SECRET
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: REDIS_URL
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
