import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const BRAND_BLUE  = '#1B5E99';
const BRAND_DARK  = '#1A1A2E';
const TEXT_GRAY   = '#555555';

// ── Helpers ───────────────────────────────────────────────────────────────────

function header(doc, title) {
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND_BLUE);
  doc.fillColor('white').fontSize(20).font('Helvetica-Bold').text('TechServ ERP', 40, 20);
  doc.fontSize(10).font('Helvetica').text('Construction · Waterproofing · Technical Services', 40, 44);
  doc.fontSize(16).font('Helvetica-Bold').text(title, 0, 22, { align: 'right', width: doc.page.width - 40 });
  doc.fillColor(BRAND_DARK).moveDown(5);
}

function section(doc, label) {
  doc.moveDown(0.5)
     .rect(40, doc.y, doc.page.width - 80, 20).fill('#EAF2FB')
     .fillColor(BRAND_BLUE).fontSize(10).font('Helvetica-Bold')
     .text(label, 48, doc.y - 16)
     .fillColor(BRAND_DARK).font('Helvetica').fontSize(10)
     .moveDown(0.8);
}

function row(doc, label, value, y) {
  doc.font('Helvetica').fillColor(TEXT_GRAY).text(label, 40, y);
  doc.font('Helvetica-Bold').fillColor(BRAND_DARK).text(value, 200, y, { width: 350 });
  return y + 18;
}

function tableHeader(doc, cols, x, y) {
  doc.rect(x, y, doc.page.width - 80, 22).fill('#1B5E99');
  let cx = x + 8;
  cols.forEach(c => {
    doc.fillColor('white').fontSize(9).font('Helvetica-Bold').text(c.label, cx, y + 6, { width: c.width });
    cx += c.width;
  });
  return y + 22;
}

function tableRow(doc, cols, values, x, y, shade) {
  if (shade) doc.rect(x, y, doc.page.width - 80, 20).fill('#F5F5F5');
  let cx = x + 8;
  cols.forEach((c, i) => {
    doc.fillColor(BRAND_DARK).fontSize(9).font('Helvetica').text(String(values[i] ?? ''), cx, y + 5, { width: c.width });
    cx += c.width;
  });
  return y + 20;
}

function footer(doc) {
  const y = doc.page.height - 50;
  doc.rect(0, y, doc.page.width, 50).fill(BRAND_BLUE);
  doc.fillColor('white').fontSize(8).font('Helvetica')
     .text('This document was generated by TechServ ERP. For queries contact your account manager.', 0, y + 18, { align: 'center' });
}

// ── Quotation PDF ─────────────────────────────────────────────────────────────

export async function generateQuotationPDF(quotation, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    header(doc, 'QUOTATION');

    // Meta info
    let y = 100;
    y = row(doc, 'Quotation No:', quotation.quotationNumber, y);
    y = row(doc, 'Date:', new Date().toLocaleDateString('en-AE'), y);
    y = row(doc, 'Valid Until:', quotation.validUntil ? new Date(quotation.validUntil).toLocaleDateString('en-AE') : '30 days', y);
    y = row(doc, 'Status:', quotation.status, y);

    section(doc, 'CLIENT DETAILS');
    y = doc.y;
    y = row(doc, 'Client:', quotation.client?.name || '—', y);
    if (quotation.client?.contactPerson) y = row(doc, 'Contact:', quotation.client.contactPerson, y);
    if (quotation.client?.email)  y = row(doc, 'Email:', quotation.client.email, y);
    if (quotation.client?.taxNumber) y = row(doc, 'TRN:', quotation.client.taxNumber, y);

    if (quotation.scopeOfWork) {
      section(doc, 'SCOPE OF WORK');
      doc.fontSize(10).fillColor(BRAND_DARK).text(quotation.scopeOfWork, 40, doc.y, { width: doc.page.width - 80 }).moveDown();
    }

    section(doc, 'BILL OF QUANTITIES');

    const cols = [
      { label: '#',           width: 24  },
      { label: 'Description', width: 180 },
      { label: 'Type',        width: 60  },
      { label: 'Unit',        width: 40  },
      { label: 'Qty',         width: 50  },
      { label: 'Unit Price',  width: 70  },
      { label: 'Total (AED)', width: 80  },
    ];

    y = tableHeader(doc, cols, 40, doc.y);
    (quotation.items || []).forEach((item, i) => {
      y = tableRow(doc, cols, [
        i + 1, item.description, item.type, item.unit,
        Number(item.quantity).toFixed(2),
        Number(item.unitPrice).toFixed(2),
        Number(item.totalPrice).toFixed(2),
      ], 40, y, i % 2 === 1);
    });

    // Totals
    y += 10;
    const totals = [
      ['Subtotal:', `AED ${Number(quotation.subtotal).toFixed(2)}`],
      [`VAT (${quotation.vatPct}%):`, `AED ${Number(quotation.vatAmount).toFixed(2)}`],
      ...(quotation.retentionPct ? [[`Retention (${quotation.retentionPct}%):`, 'As per contract']] : []),
      ['TOTAL:', `AED ${Number(quotation.totalAmount).toFixed(2)}`],
    ];
    totals.forEach(([l, v], i) => {
      const isBold = i === totals.length - 1;
      doc.rect(doc.page.width - 240, y, 200, 20).fill(isBold ? BRAND_BLUE : (i % 2 ? '#F5F5F5' : 'white'));
      doc.fillColor(isBold ? 'white' : BRAND_DARK).fontSize(isBold ? 11 : 9).font(isBold ? 'Helvetica-Bold' : 'Helvetica')
         .text(l, doc.page.width - 235, y + 5)
         .text(v, doc.page.width - 155, y + 5, { width: 110, align: 'right' });
      y += 20;
    });

    // Payment terms
    if (quotation.paymentTerms) {
      doc.moveDown(2);
      section(doc, 'PAYMENT TERMS');
      const terms = typeof quotation.paymentTerms === 'string' ? JSON.parse(quotation.paymentTerms) : quotation.paymentTerms;
      if (Array.isArray(terms)) {
        terms.forEach(t => doc.fontSize(10).fillColor(BRAND_DARK).text(`• ${t.label}: ${t.percentage}%`, 48).moveDown(0.3));
      }
    }

    if (quotation.notes) {
      doc.moveDown();
      section(doc, 'NOTES');
      doc.fontSize(10).fillColor(TEXT_GRAY).text(quotation.notes, 40);
    }

    footer(doc);
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

// ── Invoice PDF ───────────────────────────────────────────────────────────────

export async function generateInvoicePDF(invoice, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    header(doc, invoice.type.replace('_', ' '));

    let y = 100;
    y = row(doc, 'Invoice No:', invoice.invoiceNumber, y);
    y = row(doc, 'Issue Date:', new Date(invoice.issueDate).toLocaleDateString('en-AE'), y);
    y = row(doc, 'Due Date:',  new Date(invoice.dueDate).toLocaleDateString('en-AE'), y);
    y = row(doc, 'Status:', invoice.status, y);

    section(doc, 'BILLED TO');
    y = doc.y;
    y = row(doc, 'Client:', invoice.client?.name || '—', y);
    if (invoice.client?.taxNumber) y = row(doc, 'TRN:', invoice.client.taxNumber, y);
    if (invoice.project) y = row(doc, 'Project:', `${invoice.project.projectCode} — ${invoice.project.name}`, y);

    section(doc, 'ITEMS');
    const cols = [
      { label: '#',           width: 24 },
      { label: 'Description', width: 260 },
      { label: 'Qty',         width: 50 },
      { label: 'Unit Price',  width: 80 },
      { label: 'Total (AED)', width: 90 },
    ];
    y = tableHeader(doc, cols, 40, doc.y);
    (invoice.items || []).forEach((item, i) => {
      y = tableRow(doc, cols, [i+1, item.description, Number(item.quantity).toFixed(2), Number(item.unitPrice).toFixed(2), Number(item.totalPrice).toFixed(2)], 40, y, i%2===1);
    });

    y += 10;
    [
      ['Subtotal:', `AED ${Number(invoice.subtotal).toFixed(2)}`],
      [`VAT (${invoice.vatPct}%):`, `AED ${Number(invoice.vatAmount).toFixed(2)}`],
      ...(Number(invoice.retentionAmt) > 0 ? [['Retention:', `(AED ${Number(invoice.retentionAmt).toFixed(2)})`]] : []),
      ['TOTAL DUE:', `AED ${Number(invoice.totalAmount).toFixed(2)}`],
    ].forEach(([l, v], i, arr) => {
      const isBold = i === arr.length - 1;
      doc.rect(doc.page.width - 240, y, 200, 20).fill(isBold ? BRAND_BLUE : (i%2?'#F5F5F5':'white'));
      doc.fillColor(isBold?'white':BRAND_DARK).fontSize(isBold?11:9).font(isBold?'Helvetica-Bold':'Helvetica')
         .text(l, doc.page.width-235, y+5).text(v, doc.page.width-155, y+5, { width:110, align:'right' });
      y += 20;
    });

    if (invoice.notes) {
      doc.moveDown(2);
      section(doc, 'NOTES');
      doc.fontSize(10).fillColor(TEXT_GRAY).text(invoice.notes, 40);
    }

    footer(doc);
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

// ── Payslip PDF ───────────────────────────────────────────────────────────────

export async function generatePayslipPDF(employee, payrollItem, period, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    header(doc, 'PAYSLIP');

    let y = 100;
    y = row(doc, 'Employee:', `${employee.firstName} ${employee.lastName}`, y);
    y = row(doc, 'Employee Code:', employee.employeeCode, y);
    y = row(doc, 'Position:', employee.position, y);
    y = row(doc, 'Pay Period:', period, y);
    y = row(doc, 'Department:', employee.department?.name || '—', y);

    section(doc, 'EARNINGS');
    y = doc.y;
    [
      ['Basic Salary', Number(payrollItem.basicSalary)],
      ['Housing Allowance', Number(payrollItem.housingAllowance)],
      ['Transport Allowance', Number(payrollItem.transportAllowance)],
      ['Other Allowances', Number(payrollItem.otherAllowances)],
      [`Overtime (${Number(payrollItem.overtimeHours).toFixed(1)} hrs)`, Number(payrollItem.overtimePay)],
    ].filter(([,v]) => v > 0).forEach(([l, v]) => {
      y = row(doc, l, `AED ${v.toFixed(2)}`, y);
    });

    section(doc, 'DEDUCTIONS');
    y = doc.y;
    y = row(doc, 'Deductions', `AED ${Number(payrollItem.deductions).toFixed(2)}`, y);
    if (payrollItem.deductionNotes) y = row(doc, 'Notes', payrollItem.deductionNotes, y);

    section(doc, 'NET SALARY');
    doc.rect(40, doc.y, doc.page.width - 80, 40).fill(BRAND_BLUE);
    doc.fillColor('white').fontSize(16).font('Helvetica-Bold')
       .text('NET PAY:', 48, doc.y - 32)
       .text(`AED ${Number(payrollItem.netSalary).toFixed(2)}`, 0, doc.y - 32, { align: 'right', width: doc.page.width - 48 });

    footer(doc);
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}
